package gov.noaa.nws.ridge;
// Generated Jun 4, 2009 2:06:06 PM by Hibernate Tools 3.2.1.GA


import com.vividsolutions.jts.geom.Geometry;
import java.util.Date;

/**
 * RadarTimeIndex generated by hbm2java
 */
public class RadarTimeIndex  implements java.io.Serializable {


     private int id;
     private String radar;
     private String layer;
     private String radarPath;
     private Date datetime;
     private Geometry theGeom;
     private Integer vcp;
     private Float srmDirection;
     private Float srmSpeedKts;
     private Date stpStartDateTime;
     private Date stpEndDateTime;

    public RadarTimeIndex() {
    }

	
    public RadarTimeIndex(int id) {
        this.id = id;
    }
    public RadarTimeIndex(int id, String radar, String layer, String radarPath, Date datetime, Geometry theGeom) {
       this.id = id;
       this.radar = radar;
       this.layer = layer;
       this.radarPath = radarPath;
       this.datetime = datetime;
       this.theGeom = theGeom;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRadar() {
        return this.radar;
    }
    
    public void setRadar(String radar) {
        this.radar = radar;
    }
    public String getLayer() {
        return this.layer;
    }
    
    public void setLayer(String layer) {
        this.layer = layer;
    }
    public String getRadarPath() {
        return this.radarPath;
    }
    
    public void setRadarPath(String radarPath) {
        this.radarPath = radarPath;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Geometry getTheGeom() {
        return this.theGeom;
    }
    
    public void setTheGeom(Geometry theGeom) {
        this.theGeom = theGeom;
    }


	public Integer getVcp() {
		return vcp;
	}


	public void setVcp(Integer vcp) {
		this.vcp = vcp;
	}


	public Float getSrmDirection() {
		return srmDirection;
	}


	public void setSrmDirection(Float srmDirection) {
		this.srmDirection = srmDirection;
	}


	public Float getSrmSpeedKts() {
		return srmSpeedKts;
	}


	public void setSrmSpeedKts(Float srmSpeedKts) {
		this.srmSpeedKts = srmSpeedKts;
	}


	public Date getStpStartDateTime() {
		return stpStartDateTime;
	}


	public void setStpStartDateTime(Date stpStartDateTime) {
		this.stpStartDateTime = stpStartDateTime;
	}


	public Date getStpEndDateTime() {
		return stpEndDateTime;
	}


	public void setStpEndDateTime(Date stpEndDateTime) {
		this.stpEndDateTime = stpEndDateTime;
	}




}


