package org.jason;


import java.util.logging.Level;
import java.util.logging.Logger;
import org.jason.AreaPanel;
import org.jason.BarPanel;
import org.jason.DialPanel;
import org.jason.Pie3DPanel;
import org.jason.TimeSeriesPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tester.java
 *
 * Created on Jul 17, 2009, 9:38:43 AM
 */

/**
 *
 * @author Jason.Burks
 */
public class Tester extends javax.swing.JFrame {

    /** Creates new form Tester */
    public Tester() {
        
            initComponents();
//       
          //testTimeSeries();
          //testPie3DChart();
           // testAreaChart();
       testBarChart();
    }

    public void testDial(){
         DialPanel panel = new DialPanel("Test","mb");
        panel.addData(0, 40.);
         jPanel1.add(panel.getPanel());
    }

    public void testTimeSeries() {
        try {
            TimeSeriesPanel panel = new TimeSeriesPanel("test,test2", "title", "ylabel");
            panel.addData(0, 40.);
            panel.addData(1, 50.);
            Thread.sleep(1000);
            panel.addData(0, 60.);
            panel.addData(1, 100.);
            jPanel1.add(panel.getPanel());
        } catch (InterruptedException ex) {
            Logger.getLogger(Tester.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void testPie3DChart(){
         String[] categories = new String[]{"Java","C++"};
             Pie3DPanel panel = new Pie3DPanel("Test",categories,"mb");
                panel.addData(0, 40.);
                panel.addData(1, 60.);
         jPanel1.add(panel.getPanel());
    }

    public void testAreaChart() {
        try {
            AreaPanel panel = new AreaPanel("test,test2", "title", "ylabel");
            panel.addData(0, 40.);
            panel.addData(1, 50.);
            Thread.sleep(1000);
            panel.addData(0, 60.);
            panel.addData(1, 100.);
            jPanel1.add(panel.getPanel());
        } catch (InterruptedException ex) {
            Logger.getLogger(Tester.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void testBarChart() {
             String[] categories = new String[]{"Java","C++"};
            BarPanel panel = new BarPanel("title",categories,  "ylabel");
            panel.addData(0, 40.);
            panel.addData(1, 50.);

            jPanel1.add(panel.getPanel());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jButton1, gridBagConstraints);

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new java.awt.GridLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
